[project]
name = "type-annotations"
version = "0.1.0"
description = "otus-python-01-03-hw"
authors = [
    {name = "Mustafin A."}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.2.0"

